import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className='h-screen bg-gray-100 p-10'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-gray-300 p-10'>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}
